### ISSUE TITLE
Windows compile

### ISSUE THREAD

**Issue by Mk-Chan** [kelvyang/tiny-chess#1]
Hi,
    I found your post on the CCRL forum and I was successfully able to cross compile your program from Linux for Windows using the linux mingw-w64 crosscompiler with the mingw-w64 winpthreads library (with the '-static' option to avoid the dll issue).
You could add such a compile to your bin/ for CCRL testing as most of them use Windows.

**Comment by kelvyang** [comment]
Hi,
Thanks for the tip! I'll check it out.
